name: teditox
description: Simple plain text editor.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.0
  flutter: 3.35.1

dependencies:
  charset_converter: ^2.3.0
  collection: ^1.18.0
  dynamic_color: ^1.7.0
  file_picker: ^10.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  logger: ^2.0.2+1
  path_provider: ^2.1.3
  provider: ^6.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - assets/fonts/
  generate: true
  uses-material-design: true
