name: teditox
description: Simple plain text editor.
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ^3.9.0
  flutter: 3.35.3

dependencies:
  charset_converter: ^2.3.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  file_picker: ^10.3.2
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  logger: ^2.0.2+1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.3
  provider: ^6.1.5+1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - assets/fonts/Fira_Code/
    - assets/fonts/Inter/
    - assets/fonts/JetBrains_Mono/
    - assets/fonts/Nata_Sans/
    - assets/fonts/Open_Sans/
    - assets/fonts/Roboto/
    - assets/fonts/Source_Code_Pro/
  generate: true
  uses-material-design: true
