name: CI

on:
  push:
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Test
        run: flutter test --coverage

      - name: Integration Test (headless)
        run: |
          echo "Skipping integration tests on CI headless for now."
